const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dropdexDesktop', Object.freeze({
  isElectron: true,
  getRuntimeInfo: () => ipcRenderer.invoke('dropdex:runtime-info'),
  getUsbState: () => ipcRenderer.invoke('dropdex:usb-state'),
  getUsbActivityState: () => ipcRenderer.invoke('dropdex:usb-activity-state'),
  selectUsbRoot: () => ipcRenderer.invoke('dropdex:select-usb-root'),
  releaseUsb: () => ipcRenderer.invoke('dropdex:release-usb'),
  disconnectUsb: () => ipcRenderer.invoke('dropdex:disconnect-usb'),
  resolveTrackSource: (segments) => ipcRenderer.invoke('dropdex:resolve-track-source', segments),
  inspectStemAsset: (locator) => ipcRenderer.invoke('dropdex:inspect-stem-asset', locator),
  resolveStemAsset: (locator) => ipcRenderer.invoke('dropdex:resolve-stem-asset', locator),
  deleteStemAsset: (locator) => ipcRenderer.invoke('dropdex:delete-stem-asset', locator),
  prepareRouletteStems: (input) => ipcRenderer.invoke('dropdex:prepare-roulette-stems', input),
  cancelRouletteStems: (trackId) => ipcRenderer.invoke('dropdex:cancel-roulette-stems', trackId),
  metadataApplyAvailability: () => ipcRenderer.invoke('dropdex:metadata-apply-availability'),
  metadataApplyPreflight: (scope, savedDrafts) => ipcRenderer.invoke('dropdex:metadata-apply-preflight', { scope, savedDrafts }),
  metadataApply: (token, scope, savedDrafts) => ipcRenderer.invoke('dropdex:metadata-apply', { token, scope, savedDrafts }),
  metadataRecoveryVerify: (recovery) => ipcRenderer.invoke('dropdex:metadata-recovery-verify', { recovery }),
  cueApplyAvailability: () => ipcRenderer.invoke('dropdex:cue-apply-availability'),
  cueBaselineVerify: (scope, savedDrafts) => ipcRenderer.invoke('dropdex:cue-baseline-verify', { scope, savedDrafts }),
  cueApplyPreflight: (scope, savedDrafts) => ipcRenderer.invoke('dropdex:cue-apply-preflight', { scope, savedDrafts }),
  cueApply: (token, scope, savedDrafts) => ipcRenderer.invoke('dropdex:cue-apply', { token, scope, savedDrafts }),
  openExternal: (url) => ipcRenderer.invoke('dropdex:open-external', url),
}));
