"""Explicit support policy for the pyrekordbox ``DjmdCue`` model.

DropDex replaces a track's cue set as a guarded unit, so every column exposed by
our supported pyrekordbox model must have an owner.  Opaque timing/seek fields
are preserved only for the same local cue at unchanged timing; otherwise a
non-default value blocks apply rather than being silently discarded.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Optional, Sequence


EDITABLE_SEMANTIC = "editable-semantic"
PRESERVED_SEMANTIC = "preserved-semantic"
WRITER_DERIVED = "writer-derived-regenerated"
UNSUPPORTED_IRRELEVANT = "unsupported-irrelevant"
UNSUPPORTED_BLOCKING = "unsupported-blocking"
_HOT_KIND_BY_SLOT = {1: 1, 2: 2, 3: 3, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9}


@dataclass(frozen=True)
class DjmdCueFieldPolicy:
    classification: str
    rationale: str


DJMDCUE_FIELD_POLICY: Mapping[str, DjmdCueFieldPolicy] = {
    "ID": DjmdCueFieldPolicy(WRITER_DERIVED, "Row identity is regenerated; stale primary keys are never copied."),
    "ContentID": DjmdCueFieldPolicy(WRITER_DERIVED, "Derived from the strongly verified target DjmdContent."),
    "InMsec": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Canonical DropDex cue start time."),
    "InFrame": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "Higher-resolution Rekordbox timing evidence; preserved for unchanged timing."),
    "InMpegFrame": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "VBR/ABR seek timing; preserved for unchanged timing."),
    "InMpegAbs": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "VBR/ABR seek byte offset; preserved for unchanged timing."),
    "OutMsec": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Canonical DropDex loop end time / point sentinel."),
    "OutFrame": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "Higher-resolution loop timing evidence; preserved for unchanged timing."),
    "OutMpegFrame": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "VBR/ABR loop seek timing; preserved for unchanged timing."),
    "OutMpegAbs": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "VBR/ABR loop seek byte offset; preserved for unchanged timing."),
    "Kind": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Memory/Hot A-H family and slot encoding."),
    "Color": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Canonical local Memory color or Hot sentinel."),
    "ColorTableIndex": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Canonical Hot palette index; independent from Memory Color."),
    "ActiveLoop": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Active-loop state is independent from loop presence."),
    "Comment": DjmdCueFieldPolicy(EDITABLE_SEMANTIC, "Cue comment/name."),
    "BeatLoopSize": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "Encoding is not reconstructed; preserve non-default values only at unchanged timing."),
    "CueMicrosec": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "High-precision timing is not reconstructed; preserve only at unchanged timing."),
    "InPointSeekInfo": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "Opaque seek metadata is preserved, never guessed."),
    "OutPointSeekInfo": DjmdCueFieldPolicy(PRESERVED_SEMANTIC, "Opaque loop seek metadata is preserved, never guessed."),
    "ContentUUID": DjmdCueFieldPolicy(WRITER_DERIVED, "Derived from the strongly verified target DjmdContent."),
    "UUID": DjmdCueFieldPolicy(WRITER_DERIVED, "Row UUID is regenerated with the replacement row."),
    "rb_data_status": DjmdCueFieldPolicy(WRITER_DERIVED, "pyrekordbox/Rekordbox row lifecycle metadata."),
    "rb_local_data_status": DjmdCueFieldPolicy(WRITER_DERIVED, "pyrekordbox/Rekordbox row lifecycle metadata."),
    "rb_local_deleted": DjmdCueFieldPolicy(WRITER_DERIVED, "pyrekordbox/Rekordbox row lifecycle metadata."),
    "rb_local_synced": DjmdCueFieldPolicy(WRITER_DERIVED, "pyrekordbox/Rekordbox row lifecycle metadata."),
    "usn": DjmdCueFieldPolicy(WRITER_DERIVED, "Rekordbox row statistics are regenerated by the database layer."),
    "rb_local_usn": DjmdCueFieldPolicy(WRITER_DERIVED, "Rekordbox row statistics are regenerated by the database layer."),
    "created_at": DjmdCueFieldPolicy(WRITER_DERIVED, "Replacement-row creation metadata is regenerated."),
    "updated_at": DjmdCueFieldPolicy(WRITER_DERIVED, "Replacement-row update metadata is regenerated."),
}

DJMDCUE_MODEL_FIELDS = tuple(DJMDCUE_FIELD_POLICY)
PRESERVED_FIELDS = tuple(
    name for name, policy in DJMDCUE_FIELD_POLICY.items()
    if policy.classification == PRESERVED_SEMANTIC
)

# Values emitted by the established DropDex/DJcues writer when no source row has
# opaque precision/seek semantics to preserve.  Non-default values are allowed
# only through the identity+unchanged-timing preservation path below.
_CANONICAL_DEFAULTS: Mapping[str, tuple[Any, ...]] = {
    "InFrame": (0, None),
    "InMpegFrame": (0, None),
    "InMpegAbs": (0, None),
    "OutFrame": (-1, 0, None),
    "OutMpegFrame": (-1, 0, None),
    "OutMpegAbs": (-1, 0, None),
    "BeatLoopSize": (0, None),
    "CueMicrosec": (0, None),
    "InPointSeekInfo": (None, "", b""),
    "OutPointSeekInfo": (None, "", b""),
}


def _field(row: Any, name: str) -> Any:
    return row.get(name) if isinstance(row, Mapping) else getattr(row, name, None)


def model_column_names(model: Any) -> tuple[str, ...]:
    table = getattr(model, "__table__", None)
    columns = getattr(table, "columns", None)
    if columns is None:
        raise ValueError("DjmdCue model does not expose SQLAlchemy table columns.")
    names: list[str] = []
    for column in columns:
        name = getattr(column, "name", None) or getattr(column, "key", None)
        if not name:
            raise ValueError("DjmdCue model exposes an unnamed column.")
        names.append(str(name))
    return tuple(names)


def validate_model_inventory(model: Any) -> tuple[str, ...]:
    """Fail closed when the installed model changes without a reviewed policy."""
    names = model_column_names(model)
    actual = set(names)
    expected = set(DJMDCUE_MODEL_FIELDS)
    unknown = sorted(actual - expected)
    missing = sorted(expected - actual)
    if unknown or missing:
        details = []
        if unknown:
            details.append(f"unclassified fields: {', '.join(unknown)}")
        if missing:
            details.append(f"expected fields absent: {', '.join(missing)}")
        raise ValueError("DjmdCue support-policy inventory mismatch (" + "; ".join(details) + ").")
    return names


def nondefault_preserved_fields(row: Any) -> tuple[str, ...]:
    result: list[str] = []
    for field in PRESERVED_FIELDS:
        value = _field(row, field)
        if value not in _CANONICAL_DEFAULTS[field]:
            result.append(field)
    return tuple(result)


def timing_matches(row: Any, *, start_ms: int, end_ms: Optional[int]) -> bool:
    try:
        current_start = int(_field(row, "InMsec"))
        current_out = int(_field(row, "OutMsec"))
    except (TypeError, ValueError):
        return False
    desired_out = int(end_ms) if end_ms is not None else -1
    return current_start == int(start_ms) and current_out == desired_out


def preserved_values(row: Any) -> dict[str, Any]:
    return {field: _field(row, field) for field in PRESERVED_FIELDS}


def preservation_blocker(
    row: Any,
    *,
    desired_id: Optional[str],
    desired_start_ms: int,
    desired_end_ms: Optional[int],
    allow_semantic_rebind: bool = False,
) -> Optional[str]:
    """Return a blocker when opaque non-default values cannot be safely carried."""
    nondefault = nondefault_preserved_fields(row)
    if not nondefault:
        return None
    current_id = _field(row, "ID")
    if (current_id is None or desired_id is None or str(current_id) != str(desired_id)) and not allow_semantic_rebind:
        return (
            f"Current local cue {current_id or '?'} contains non-default preserved DjmdCue fields "
            f"({', '.join(nondefault)}) but the desired cue cannot prove the same local cue identity."
        )
    if not timing_matches(row, start_ms=desired_start_ms, end_ms=desired_end_ms):
        return (
            f"Current local cue {current_id} contains non-default preserved DjmdCue fields "
            f"({', '.join(nondefault)}) and its timing changed; DropDex cannot safely regenerate those values."
        )
    return None


def _desired_kind(cue: Any) -> Optional[int]:
    if getattr(cue, "family", None) == "memory":
        return 0
    slot = getattr(cue, "hot_cue_slot", None)
    return _HOT_KIND_BY_SLOT.get(slot)


def _semantic_timing_match(row: Any, cue: Any) -> bool:
    kind = _field(row, "Kind")
    try:
        current_kind = int(kind)
    except (TypeError, ValueError):
        return False
    desired_kind = _desired_kind(cue)
    if desired_kind != current_kind:
        return False
    return timing_matches(
        row,
        start_ms=int(cue.start_ms),
        end_ms=int(cue.end_ms) if cue.end_ms is not None else None,
    )


def find_matching_desired_for_preservation(
    row: Any, desired_cues: Sequence[Any]
) -> tuple[Optional[Any], str]:
    """Resolve preservation ownership without trusting array order.

    ``stable-id`` survives ordinary hydration. ``semantic-rebind`` is used after
    complete-set replacement regenerated row IDs but the same unique Kind/timing
    is still present. A changed-timing Kind match is returned so preflight can
    block unsafe regeneration. Ambiguity always fails closed.
    """
    current_id = _field(row, "ID")
    if current_id is not None:
        stable = [
            cue for cue in desired_cues
            if getattr(cue, "rekordbox_cue_id", None) is not None
            and str(getattr(cue, "rekordbox_cue_id")) == str(current_id)
        ]
        if len(stable) == 1:
            return stable[0], "stable-id"
        if len(stable) > 1:
            return None, "ambiguous"

    semantic = [cue for cue in desired_cues if _semantic_timing_match(row, cue)]
    if len(semantic) == 1:
        return semantic[0], "semantic-rebind"
    if len(semantic) > 1:
        return None, "ambiguous"

    try:
        current_kind = int(_field(row, "Kind"))
    except (TypeError, ValueError):
        return None, "none"
    same_kind = [cue for cue in desired_cues if _desired_kind(cue) == current_kind]
    if len(same_kind) == 1:
        return same_kind[0], "kind-reposition"
    if len(same_kind) > 1:
        return None, "ambiguous"
    return None, "removed"


def source_row_for_preservation(existing_rows: Sequence[Any], cue: Any) -> Optional[Any]:
    """Find one current row whose opaque fields can safely follow this desired cue."""
    cue_id = getattr(cue, "rekordbox_cue_id", None)
    if cue_id is not None:
        for row in existing_rows:
            if _field(row, "ID") is not None and str(_field(row, "ID")) == str(cue_id):
                if _semantic_timing_match(row, cue):
                    return row
                return None
    semantic = [row for row in existing_rows if _semantic_timing_match(row, cue)]
    return semantic[0] if len(semantic) == 1 else None
